//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuProStore.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TownEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TownEntity()
        {
            this.Products = new HashSet<ProductEntity>();
        }
    
        public int ID { get; set; }
        public int RegionId { get; set; }
        public string TownName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntity> Products { get; set; }
        public virtual RegionEntity Region { get; set; }
    }
}
